server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login_system?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Root123
    driver-class-name: com.mysql.cj.jdbc.Driver

# Swagger open on /swagger-ui.html

jwt:
  key: ChangeThisKeyToAStrongSecret_1234567890
  issuer: login-system
  audience: login-system
  expiresHours: 2

